### ISSUE TITLE
Day00 - SQL (Postgres)

### ISSUE THREAD

**Issue by fxbabin** [42-AI/bootcamp_data-engineering#1]
- [x] Intro of day00
- [x] Ex00: Setup #2 
- [x] Ex01: Clean #3 
- [x] Ex02: Normalize #4 
- [x] Ex03: Populate #5
- [x] Ex04: Top_100 #9
- [x] Ex05: Name_lang_5-10 #15 
- [x] Ex06: K-first #16 
- [x] Ex07: Devs #17 
- [x] Ex08: Battle_royale #18 
- [x] Ex09: Benefits #19 
- [x] Ex10: Sweet_spot #13   
- [x] Ex11: Price_analysis #14  
- [x] Ex12: Worldwide #20 
- [x] Ex13: Sample #21
